branches:
  only:
  - main

language: go

go:
  - 1.15.x
  - 1.16.x

env:
  global:
    # - secure: FdVuGnK3+qY7ndVb6YP8Y13YjvLZly3PM+W+tsR77WGVDGm9oSSLXkCGAs88laMHzMMjHBvMEEoYL3gosWsk2MmOwr/LFxe7/fyH8IXeJsYFGViHl8ybbKnAlhKUPKKbpRaYb3G3OtClm/R4ONoX0ok/IHlkjF6iF9AO8rlRRqJyHzVlnIegNzaPAGaVl3yQDL3+skznDee/ZUOkz197t0ameVWICmzCXTBIyeCD4AUWbtn+i/VLVFDd6o3twlFOhhnAkrL0CbFBChdKB2RRDDQEIzXrdptj+i/96JL9BA3aQGph+76GSwzfO5Uk68dCglFdwMmZlm8+B17SaTt9ve6/4RTDWxEBPz5CY6+0KhsKGIXa5te86T6TX7NsuRUqTEwb7SjjRH1aQZ9FumC7nHinUVY+ObCoB+6XtobXWXeU670KUjCTTgPa9i0DzDDnxBsjwSFP4iwK60u+plr3sMqugto3Iky460nBz53OsFkfLE73EcXGm3LATM5gwN2x959mDY6zzTVW/P6ynT2emEVH43I8Qdz5qrZP3iah6ST93knwB6/eLzn9nwWocgYyJZhFxVxF/rnhwdXfXnP+Q3h6xnQj2kzNXFt1/gG4AJecPRUjk9e5cHMyOse7mkxKsALUE1TA+HOtlnVmcbZktYm7QjRLukG6I1JBGYOiT+w=
    # - secure: dtPCZ/vH6Q1eq81T9pC9o9pMMKhEOK0tAQU3rHVh2cmUMhtNUru350g/bUWMZg4+n+nah3IaQGKC7d0K07O3ltr/yrAGvwJFn4RWKAabbNtauNdJlWRQhrNZrwadkzhfb9xu7OXQSKfIr+WERllYVnzpRI9Z4x2tG6YT1wviuU5PW3/7y5c+1nKXz+QcLrs7D44J/yA7l03Yusq5tUUrv/iBkmk+gDXhHvy5sODUM5ejDW5c6swkY5x/UsK1wJIivbjkLuwK2Al3rYXdmkkXGRoFiw4rTgre9pen2gpTlfuIkuLZSj/m+lSpdJloI8BlNkQQ1l8sXTCfa2terDb/0S0vYwFhiS02IcCO4+U9XslLa8FOeSG88gEdOTBgsITTLMqdnpIChNZhP/25Epwk4b8cb72leUgrdQuZ4bUDxAiUTHA1pNzTpuaxHsHmM8hB6U503kn3jfT9LUTArdeWd2wWAX+6aKyI/H1KW+QLtKCtT5q+u+W7aAvKxJ3RrUjLVqZXDpy3QO7fFq6grbcbLfhZrRSXvuGVYbSxfJJKUxWwoWePY14/c4B/ZzRDQlnskR4Pp4b9I/KeSDm/F7v51ULw9agUmrCRnzz9U2U7l7uUWwoUEn8nQzQwcEKM2fzeXXiVRPItZCcJIjPCx+8I1sy/Ljj/fC9bytS2j32dTTA=
    - secure: oZ5NwfAj2ssq8wCceKuCiazFTtONCXDoKdwAevlNhI41MfORdPtalPWFBw8xfUFil8OceYXWOpj0WSsZtHPfp48zpXjCmoo3pY0F2xTtkczSA7f8uYWx3CJ0Litn7J5xQdRPRYOFiIoTo2+vGAeZhH1wCeCGP2xh0QiWPT6xUDmlzvYBhS6yVmQ1YXF3xR0dj5b65A6Caa3YoJ9nKPI94YTlq47DKRhF+0v1fQfAIC4MvcBCgApZclzmSctaU2cP1fqHj8eiqXIIumVLwtMgEenyhrEgk3+o1MO6Hp38p64IoY9YmJI1HRM+xn4RndPrE9tEKla6Z51UfrG27roARyHpJTZQT87IZ3kYayIvBG8J2k3dNzwrgJY3tVymw+ZgnO7Gg/gQ5VCRsqPoXDfq4CfAdqkmTmWiWmQ2MYkkgecBqilTUlvwL19XyTmBIS8DrPKVG+VHF+pIpBoDaqclilm1KuxUve2upMVRiRAEkUTiKtp27HJ4xt4YS0kyXSS+RgmWLmgqAnuaIFXXUd9y7xkTsun+mNpr0+yINqGeVJdVr0ecVSOTXt9lbX+uHkinyesNZy8E1u3KkiBpK+sNoE7QxhM99Mf7mxgO2u9qrfdDKeEBALz/3/kRB74NgVgrG3vk3yOH2GxdlzkmNWDs1H9izVTJGzFHGGLb2WJEvRU=
services:
  - docker

before_install:
  - go get github.com/devops-unicorn/buoy

install:
  - # skip

script:
  - go mod download
  - go test -v .
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o buoy .
  - echo $GH_PERSONAL_TOKEN
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_PERSONAL_TOKEN
  file: buoy
  draft: true
  on:
    repo: devops-unicorn/buoy
    all_branches: true
    # tags: true

# script:
#   - go test -v .
#   - export TAG=$(git ls-remote --tags | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | tail -n 1)
#   - export COMMIT=$(git ls-remote | grep refs/heads/main | cut -f 1)
#   - docker build -t devopsunicorn/buoy:$COMMIT .
#   # docker run -d --name test devopsunicorn/buoy:$COMMIT
#   - docker ps -a
#   # Testing
#   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
#   - echo $TAG
#   - echo $COMMIT
#   - docker tag devopsunicorn/buoy:$COMMIT devopsunicorn/buoy:$TAG  
#   - docker push devopsunicorn/buoy:$TAG

# after_success:
#   - echo $TAG
#   - echo $COMMIT
#   - docker tag devopsunicorn/buoy:$COMMIT devopsunicorn/buoy:$TAG  
#   - docker push devopsunicorn/buoy:$TAG