name: build and publish docker image
on: repository_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images:
          devopsunicorn/buoy
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tagName.outputs.tag }} 
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "devopsunicorn/buoy"
        TAG_NAME: ${{ steps.meta.outputs.version }}
        LATEST: "true"

    # - name: Docker Build & Push to GitHub Package
    #   uses: opspresso/action-docker@master
    #   with:
    #     args: --docker
    #   env:
    #     USERNAME: ${{ secrets.GITHUB_USERNAME }}
    #     PASSWORD: ${{ secrets.GH_PERSONAL_TOKEN }}
    #     REGISTRY: "docker.pkg.github.com"
    #     DOCKERFILE: "Dockerfile"
    #     IMAGE_NAME: buoy
    #     TAG_NAME: ${{ steps.tagName.outputs.tag }} 
    #     LATEST: "true"
