name: build and publish docker image
on:
  push:
    branch: [main]
  pull_request:
    branch: [main]
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Retrieve version
      run: |
        echo ::set-output name=TAG_NAME::$(git describe --abbrev=0)
      id: version
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
    #   with:
    #     tag_name: ${{ env.TAG_NAME }}
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "devopsunicorn2021/buoy"
    #    TAG_NAME: ${{ steps.version.outputs.TAG_NAME }}  
        TAG_NAME: "0.0.1"
        LATEST: "true"

    # - name: Docker Build & Push to GitHub Package
    #   uses: opspresso/action-docker@master
    #   with:
    #     args: --docker
    #   env:
    #     USERNAME: ${{ secrets.GITHUB_USERNAME }}
    #     PASSWORD: ${{ secrets.GH_PERSONAL_TOKEN }}
    #     REGISTRY: "docker.pkg.github.com"
    #     DOCKERFILE: "Dockerfile"
    #     IMAGE_NAME: buoy
    #     TAG_NAME: ${{ steps.previoustag.outputs.tag }}
    #     LATEST: "true"
