name: build and publish docker image
on:
  push:
    branch: [master]
  pull_request:
    branch: [master]
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: devopsunicorn2021/buoy
        # releases-only: false
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
      id: buoy_id

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "devopsunicorn2021/buoy"
        TAG_NAME: ${{ steps.buoy_id.outputs.tag }}
        LATEST: "true"

    # - name: Docker Build & Push to GitHub Package
    #   uses: opspresso/action-docker@master
    #   with:
    #     args: --docker
    #   env:
    #     USERNAME: ${{ secrets.GITHUB_USERNAME }}
    #     PASSWORD: ${{ secrets.GH_PERSONAL_TOKEN }}
    #     REGISTRY: "docker.pkg.github.com"
    #     DOCKERFILE: "Dockerfile"
    #     IMAGE_NAME: buoy
    #     TAG_NAME: ${{ steps.previoustag.outputs.tag }}
    #     LATEST: "true"