name: build and publish docker image
on:
  pull_request:
    branches: 
      - main
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get tag name
      id: get_tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tagName.outputs.tag }} 
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "devopsunicorn/buoy"
        TAG_NAME: ${{ steps.get_tag.outputs.SOURCE_TAG }}
        LATEST: "true"

    # - name: Docker Build & Push to GitHub Package
    #   uses: opspresso/action-docker@master
    #   with:
    #     args: --docker
    #   env:
    #     USERNAME: ${{ secrets.GITHUB_USERNAME }}
    #     PASSWORD: ${{ secrets.GH_PERSONAL_TOKEN }}
    #     REGISTRY: "docker.pkg.github.com"
    #     DOCKERFILE: "Dockerfile"
    #     IMAGE_NAME: buoy
    #     TAG_NAME: ${{ steps.tagName.outputs.tag }} 
    #     LATEST: "true"
